-- =============================================
-- HOSPITAL ANALYTICS SQL SCRIPT
-- Author: Generated by T Tsamai
-- Description: Comprehensive SQL queries for financial, HR,
-- operational, and strategic analysis of hospital data
-- =============================================

/* ================================
   FINANCIAL PERFORMANCE
================================= */

-- 1. Total monthly expense per department
SELECT Department, Month, SUM(Utilities + Salaries + Supplies + Maintenance) AS TotalExpense
FROM department_expenses
GROUP BY Department, Month
ORDER BY Department, Month;

-- 2. Departments with highest operational costs
SELECT Department, SUM(Utilities + Salaries + Supplies + Maintenance) AS AnnualExpense
FROM department_expenses
GROUP BY Department
ORDER BY AnnualExpense DESC;

-- 3. Average cost per patient admission
SELECT ROUND(SUM(Utilities + Salaries + Supplies + Maintenance) / (SELECT COUNT(*) FROM patient_admissions), 2) AS AvgCostPerAdmission
FROM department_expenses;

-- 4. Revenue lost due to rejected insurance claims
SELECT SUM(ClaimAmount - ApprovedAmount) AS LostRevenue
FROM insurance_claims
WHERE Status = 'Rejected';

-- 5. Approval rate of insurance claims by provider
SELECT InsuranceProvider, ROUND(SUM(CASE WHEN Status = 'Approved' THEN 1 ELSE 0 END) * 100.0 / COUNT(*), 2) AS ApprovalRate
FROM insurance_claims
GROUP BY InsuranceProvider;

-- 6. Percentage of expenses: salaries vs equipment vs operations
WITH totals AS (
    SELECT
        (SELECT SUM(Salaries) FROM department_expenses) AS SalaryTotal,
        (SELECT SUM(Cost) FROM equipment_inventory) AS EquipmentTotal,
        (SELECT SUM(Utilities + Supplies + Maintenance) FROM department_expenses) AS OperationsTotal
),
combined AS (
    SELECT *, (SalaryTotal + EquipmentTotal + OperationsTotal) AS GrandTotal FROM totals
)
SELECT
    ROUND(SalaryTotal * 100.0 / GrandTotal, 2) AS SalaryPercentage,
    ROUND(EquipmentTotal * 100.0 / GrandTotal, 2) AS EquipmentPercentage,
    ROUND(OperationsTotal * 100.0 / GrandTotal, 2) AS OperationsPercentage
FROM combined;


/* ================================
   HUMAN RESOURCES
================================= */

-- 7. Total monthly salary expenditure
SELECT Department, SUM(MonthlySalary) AS TotalSalary
FROM staff_salaries
GROUP BY Department
ORDER BY TotalSalary DESC;

-- 8. Roles with highest compensation
SELECT Role, ROUND(AVG(MonthlySalary), 2) AS AvgSalary
FROM staff_salaries
GROUP BY Role
ORDER BY AvgSalary DESC;

-- 9. Departments with high staff costs vs patient volume
SELECT s.Department, SUM(s.MonthlySalary) AS StaffCost, COUNT(p.PatientID) AS PatientVolume,
ROUND(SUM(s.MonthlySalary) * 1.0 / COUNT(p.PatientID), 2) AS CostPerPatient
FROM staff_salaries s
JOIN patient_admissions p ON s.Department = p.Department
GROUP BY s.Department
ORDER BY CostPerPatient DESC;

-- 10. Staff-to-patient ratio
SELECT s.Department, COUNT(DISTINCT s.StaffID) AS StaffCount, COUNT(DISTINCT p.PatientID) AS PatientCount,
ROUND(COUNT(DISTINCT s.StaffID) * 1.0 / COUNT(DISTINCT p.PatientID), 2) AS Ratio
FROM staff_salaries s
JOIN patient_admissions p ON s.Department = p.Department
GROUP BY s.Department;

-- 11. Salary correlation with department performance (proxy: expenses)
SELECT Department, ROUND(AVG(MonthlySalary), 2) AS AvgSalary,
(SELECT SUM(Utilities + Salaries + Supplies + Maintenance) FROM department_expenses d WHERE d.Department = s.Department) AS TotalExpense
FROM staff_salaries s
GROUP BY Department;


/* ================================
   OPERATIONAL EFFICIENCY
================================= */

-- 12. Average length of stay per department
SELECT Department, ROUND(AVG(julianday(DischargeDate) - julianday(AdmissionDate)), 2) AS AvgStay
FROM patient_admissions
GROUP BY Department;

-- 13. Departments with highest patient turnover
SELECT Department, COUNT(*) AS Admissions
FROM patient_admissions
GROUP BY Department
ORDER BY Admissions DESC;

-- 14. Seasonal trends in admissions
SELECT strftime('%Y-%m', AdmissionDate) AS Month, COUNT(*) AS Admissions
FROM patient_admissions
GROUP BY Month
ORDER BY Month;

-- 15. Equipment items out of service
SELECT COUNT(*) AS OutOfServiceCount
FROM equipment_inventory
WHERE Status = 'Out of Service';

-- 16. Average maintenance cost per equipment type
SELECT Name AS EquipmentType, ROUND(AVG(Cost), 2) AS AvgCost
FROM equipment_inventory
WHERE Status = 'Under Maintenance'
GROUP BY Name;


/* ================================
   STRATEGIC PLANNING
================================= */

-- 17. Departments overspending (above average)
SELECT Department, SUM(Utilities + Salaries + Supplies + Maintenance) AS TotalExpense
FROM department_expenses
GROUP BY Department
HAVING TotalExpense > (SELECT AVG(Utilities + Salaries + Supplies + Maintenance) FROM department_expenses);

-- 18. ROI on equipment purchases (proxy: operational vs total cost)
SELECT Department, ROUND(SUM(CASE WHEN Status = 'Operational' THEN Cost ELSE 0 END) * 1.0 / SUM(Cost), 2) AS ROI
FROM equipment_inventory
GROUP BY Department;

-- 19. Claim amounts vs treatment costs
SELECT (SELECT SUM(ClaimAmount) FROM insurance_claims) AS TotalClaims,
(SELECT SUM(Utilities + Salaries + Supplies + Maintenance) FROM department_expenses) AS TotalTreatmentCost;

-- 20. Diagnosis patterns suggesting resource reallocation
SELECT Diagnosis, COUNT(*) AS Frequency
FROM patient_admissions
GROUP BY Diagnosis
ORDER BY Frequency DESC;
